a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('O valor {} só tem espaços? '.format(a), a.isspace())
print('{} é um número? '.format(a), a.isnumeric())
print('{} é alfabetico? '.format(a), a.isalpha())
print('{} é alfanumerico? '.format(a), a.isalnum())
print('{} está em maiusculo? '.format(a), a.isupper())
print('{} está em minusculo? '.format(a), a.islower())
print('{} está capitalizada? '.format(a), a.istitle())
